apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-app-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: k8s-hello-app-deploy
  template:
    metadata:
      labels:
        app: k8s-hello-app-deploy
    spec:
      containers:
      - name: k8s-hello-app-deploy
        image: conan736/k8s-hello-app:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 7000
